#!/bin/sh

# switch to first workspace for a nicer view
hyprctl dispatch workspace 1 && sleep 0.2

# pause cmus
cmus-remote -C player-pause-playback

# change layouts back to english so i don't get locked out
hyprctl keyword input:kb_layout us,ru

# start the swaylock daemon
exec swaylockd
