#!/bin/sh

cd ~

# nvidia-specific stuff
export LIBVA_DRIVER_NAME=nvidia
export CLUTTER_BACKEND=wayland
export XDG_SESSION_TYPE=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export MOZ_ENABLE_WAYLAND=1
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export WLR_BACKEND=vulkan
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

# bemenu config, cuz hyprland hates strings in its config
BG_DIM='#181825'
BG='#181825'
BG_BRIGHT='#313244'
ACCENT='#cba6f7'
FG='#b4befe'

export BEMENU_OPTS="-i -p '' --fn --scrollbar none -H 28 -W 0.5 --fn 'JetBrains Mono Nerd Font 12' --tb $BG_DIM --tf $ACCENT --fb $BG_DIM --ff $FG --nb $BG_DIM --nf $FG --hb $BG_DIM --hf $ACCENT --sb $BG_DIM --sf $ACCENT"

# common envvars
export GRIM_DEFAULT_DIR=~/media/images/grim-screenshots/
export XDG_DESKTOP_DIR=~/desktop/

exec Hyprland
